In [3]:
import numpy as np

In [11]:
data = np.arange(9).reshape((3, 3, 1))

data = data.astype("float")

data[0][0][1] = np.nan

data

array([[[ 0., nan,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]]])

In [44]:
data = np.arange(9).reshape((3, 3))
data = data.astype("float")
zeros_ = np.zeros(data.shape)

In [52]:
data

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [45]:
data.shape

(3, 3)

In [46]:
zeros_.shape

(3, 3)

In [55]:
data_ = np.stack((data, zeros_))
data_.shape

(2, 3, 3)

In [56]:
data_

array([[[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
np.mean(data)

nan

In [12]:
data = np.arange(100)

In [15]:
data[-25:]

array([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])